"""Multi-dimensional rank topology.

This module is deliberately **pure arithmetic**: it never touches
``torch.distributed``.  That makes every coordinate calculation unit-testable
in a single process, which is exactly what you want, because an off-by-one in
the rank layout produces a *hang*, not an exception.

The layout
----------
A rank is a mixed-radix number over four digits.  Reading from the most
significant digit to the least significant one::

    rank = ((dp * S + sh) * Q + sq) * T + tp

    dp in [0, data_parallel_size)      most significant  (slowest varying)
    sh in [0, shard_parallel_size)     S = shard_parallel_size
    sq in [0, sequence_parallel_size)  Q = sequence_parallel_size
    tp in [0, tensor_parallel_size)    least significant (fastest varying)

Why this order and not some other one?  Ranks that are numerically adjacent are
usually topologically adjacent as well: consecutive ranks share a node, then a
NUMA domain, then an NVLink island.  The dimension with the *highest*
communication volume per step therefore belongs in the least significant digit.
Ranked by traffic:

============================  ==========================================
Dimension                     Traffic per training step
============================  ==========================================
tensor parallel               2 collectives *per layer* over full
                              activations -- by far the heaviest
sequence parallel             1--2 collectives per layer over activations
FSDP shard                    1 all-gather + 1 reduce-scatter *per unit*
                              over parameters
data parallel                 1 all-reduce per step over gradients
============================  ==========================================

Hence ``tensor`` innermost, ``data_parallel`` outermost.  A hybrid-sharded job
(``data_parallel_size > 1`` and ``shard_parallel_size > 1``) then naturally
shards *within* a node and replicates *across* nodes, which is the standard
HSDP placement.

An 8-rank worked example
------------------------
``dp=2, shard=2, sequence=1, tensor=2`` gives ``2 * 2 * 1 * 2 = 8``::

    rank | dp sh sq tp | data_parallel group | shard group | tensor group
    -----+-------------+---------------------+-------------+-------------
       0 |  0  0  0  0 | (0, 4)              | (0, 2)      | (0, 1)
       1 |  0  0  0  1 | (1, 5)              | (1, 3)      | (0, 1)
       2 |  0  1  0  0 | (2, 6)              | (0, 2)      | (2, 3)
       3 |  0  1  0  1 | (3, 7)              | (1, 3)      | (2, 3)
       4 |  1  0  0  0 | (0, 4)              | (4, 6)      | (4, 5)
       5 |  1  0  0  1 | (1, 5)              | (5, 7)      | (4, 5)
       6 |  1  1  0  0 | (2, 6)              | (4, 6)      | (6, 7)
       7 |  1  1  0  1 | (3, 7)              | (5, 7)      | (6, 7)

Read a row as: "rank 3 holds tensor-parallel slice 1 of shard 1 of replica 0."
Its gradient shard is all-reduced with rank 7 (the other replica of the same
shard/slice), reduce-scattered with rank 1 (the other shard of the same
replica/slice), and its activations are all-reduced with rank 2 (the other
tensor slice).
"""

from __future__ import annotations

import itertools
from collections.abc import Iterable
from dataclasses import dataclass

from ..config import SequenceParallelMode, TopologyConfig
from ..errors import TopologyError, format_error

__all__ = [
    "COMPOSITE_GROUPS",
    "DIMENSIONS",
    "ParallelTopology",
    "RankCoordinates",
]

#: Canonical dimension order, most significant digit first.  Every rank list in
#: this project is generated by iterating dimensions in this order, which is
#: what makes group construction deterministic across ranks.
DIMENSIONS: tuple[str, ...] = ("data_parallel", "shard", "sequence", "tensor")

#: Named groups that span more than one dimension.
#:
#: ``dp_shard``
#:     Every rank that processes a *different* slice of the global batch while
#:     holding (some part of) the same parameters.  Losses and metrics are
#:     reduced over this group -- reducing over the whole world would count the
#:     same sample once per tensor-parallel rank.
#: ``tensor_sequence``
#:     The "model parallel" group: every rank that collaborates on the *same*
#:     batch slice.  Ranks in this group must see identical input data.
#: ``world``
#:     All ranks.  Present so that code paths which genuinely need a global
#:     collective (for example the global gradient norm) can name it
#:     explicitly rather than defaulting to ``None``.
COMPOSITE_GROUPS: dict[str, tuple[str, ...]] = {
    "dp_shard": ("data_parallel", "shard"),
    "tensor_sequence": ("sequence", "tensor"),
    "world": DIMENSIONS,
}


@dataclass(frozen=True)
class RankCoordinates:
    """A rank's position in the four-dimensional grid.

    Attributes:
        data_parallel: Replica index.
        shard: FSDP shard index.
        sequence: Sequence-parallel index (always ``0`` unless the topology
            uses ``sequence_parallel_mode='independent'``).
        tensor: Tensor-parallel slice index.
    """

    data_parallel: int
    shard: int
    sequence: int
    tensor: int

    def as_tuple(self) -> tuple[int, int, int, int]:
        """Return the coordinates in canonical :data:`DIMENSIONS` order."""
        return (self.data_parallel, self.shard, self.sequence, self.tensor)

    def __getitem__(self, dimension: str) -> int:
        """Look a coordinate up by dimension name.

        Args:
            dimension: One of :data:`DIMENSIONS`.

        Returns:
            The coordinate along that dimension.

        Raises:
            KeyError: If ``dimension`` is not a known dimension name.
        """
        if dimension not in DIMENSIONS:
            raise KeyError(f"unknown dimension {dimension!r}; expected one of {DIMENSIONS}")
        return int(getattr(self, dimension))

    def label(self) -> str:
        """Compact human label such as ``"dp0/sh1/sq0/tp1"``."""
        return f"dp{self.data_parallel}/sh{self.shard}/sq{self.sequence}/tp{self.tensor}"


class ParallelTopology:
    """Maps between global ranks, grid coordinates and process-group membership.

    Args:
        config: Dimension sizes and the sequence-parallel mode.
        world_size: Number of processes in the job.  Must equal
            ``config.world_size``.

    Raises:
        TopologyError: If the configuration does not factor ``world_size``.

    Example:
        >>> from hybrid_training.config import TopologyConfig
        >>> topo = ParallelTopology(TopologyConfig(data_parallel_size=2,
        ...                                        shard_parallel_size=2,
        ...                                        tensor_parallel_size=2), 8)
        >>> topo.coordinates_of(3).label()
        'dp0/sh1/sq0/tp1'
        >>> topo.group_ranks("tensor", rank=3)
        (2, 3)
        >>> topo.group_ranks("data_parallel", rank=3)
        (3, 7)
    """

    def __init__(self, config: TopologyConfig, world_size: int) -> None:
        config.validate_against_world_size(world_size)
        self._config = config
        self._world_size = world_size
        self._sizes: dict[str, int] = {
            "data_parallel": config.data_parallel_size,
            "shard": config.shard_parallel_size,
            "sequence": config.sequence_parallel_size,
            "tensor": config.tensor_parallel_size,
        }
        # Radix weights, computed once.  weight[d] is how much the global rank
        # increases when coordinate d increases by one.
        self._weights: dict[str, int] = {}
        weight = 1
        for dimension in reversed(DIMENSIONS):
            self._weights[dimension] = weight
            weight *= self._sizes[dimension]

    # -- basic accessors ----------------------------------------------------
    @property
    def config(self) -> TopologyConfig:
        """The configuration this topology was built from."""
        return self._config

    @property
    def world_size(self) -> int:
        """Number of ranks covered by the grid."""
        return self._world_size

    @property
    def sizes(self) -> dict[str, int]:
        """Copy of the per-dimension sizes, keyed by dimension name."""
        return dict(self._sizes)

    def size(self, dimension: str) -> int:
        """Return the size of one dimension.

        Args:
            dimension: A name from :data:`DIMENSIONS` or
                :data:`COMPOSITE_GROUPS`.

        Returns:
            The number of ranks in a group along that dimension (the product
            of the member dimensions for a composite group).

        Raises:
            TopologyError: If the name is unknown.
        """
        dims = self._resolve(dimension)
        product = 1
        for name in dims:
            product *= self._sizes[name]
        return product

    # -- coordinate maths ---------------------------------------------------
    def coordinates_of(self, rank: int) -> RankCoordinates:
        """Decompose a global rank into grid coordinates.

        Args:
            rank: Global rank in ``[0, world_size)``.

        Returns:
            The rank's coordinates.

        Raises:
            TopologyError: If ``rank`` is out of range.
        """
        self._check_rank(rank)
        remainder = rank
        coords: dict[str, int] = {}
        for dimension in reversed(DIMENSIONS):
            size = self._sizes[dimension]
            coords[dimension] = remainder % size
            remainder //= size
        return RankCoordinates(
            data_parallel=coords["data_parallel"],
            shard=coords["shard"],
            sequence=coords["sequence"],
            tensor=coords["tensor"],
        )

    def rank_of(self, coordinates: RankCoordinates | Iterable[int]) -> int:
        """Compose grid coordinates back into a global rank.

        Args:
            coordinates: Either a :class:`RankCoordinates` or an iterable of
                four integers in :data:`DIMENSIONS` order.

        Returns:
            The global rank.

        Raises:
            TopologyError: If any coordinate is out of range.
        """
        values = (
            coordinates.as_tuple()
            if isinstance(coordinates, RankCoordinates)
            else tuple(coordinates)
        )
        if len(values) != len(DIMENSIONS):
            raise TopologyError(
                format_error(
                    "topology.rank_of",
                    "wrong number of coordinates",
                    expected=len(DIMENSIONS),
                    observed=len(values),
                    resolution=f"pass one coordinate per dimension {DIMENSIONS}",
                )
            )
        rank = 0
        for dimension, value in zip(DIMENSIONS, values):
            size = self._sizes[dimension]
            if not 0 <= value < size:
                raise TopologyError(
                    format_error(
                        "topology.rank_of",
                        f"coordinate for dimension {dimension!r} is out of range",
                        expected=f"0 <= c < {size}",
                        observed=value,
                        resolution="check the coordinate you constructed",
                    )
                )
            rank += value * self._weights[dimension]
        return rank

    # -- group membership ---------------------------------------------------
    def group_ranks(self, dimension: str, rank: int) -> tuple[int, ...]:
        """Return the ranks that share a group with ``rank`` along ``dimension``.

        A group along dimension *d* holds every rank whose coordinates match
        ``rank``'s in *all other* dimensions.  The returned tuple is sorted
        ascending, which is also the order produced by iterating the varying
        dimensions in canonical order.

        Args:
            dimension: A name from :data:`DIMENSIONS` or
                :data:`COMPOSITE_GROUPS`.
            rank: The rank whose group is requested.

        Returns:
            Ascending tuple of global ranks, always containing ``rank``.

        Raises:
            TopologyError: If the dimension name or rank is invalid.
        """
        self._check_rank(rank)
        varying = self._resolve(dimension)
        base = self.coordinates_of(rank)
        ranges = [range(self._sizes[d]) if d in varying else (base[d],) for d in DIMENSIONS]
        return tuple(sorted(self.rank_of(combo) for combo in itertools.product(*ranges)))

    def all_group_rank_lists(self, dimension: str) -> tuple[tuple[int, ...], ...]:
        """Return *every* group along ``dimension``, in deterministic order.

        The result partitions ``range(world_size)``.  Groups are ordered by
        their smallest member, which guarantees that every rank enumerates them
        identically -- the precondition for calling ``dist.new_group`` in a
        consistent order (see :mod:`hybrid_training.distributed.groups`).

        Args:
            dimension: A name from :data:`DIMENSIONS` or
                :data:`COMPOSITE_GROUPS`.

        Returns:
            Tuple of ascending rank tuples.
        """
        varying = self._resolve(dimension)
        fixed = [d for d in DIMENSIONS if d not in varying]
        groups: list[tuple[int, ...]] = []
        for fixed_values in itertools.product(*(range(self._sizes[d]) for d in fixed)):
            fixed_map = dict(zip(fixed, fixed_values))
            ranges = [
                range(self._sizes[d]) if d in varying else (fixed_map[d],) for d in DIMENSIONS
            ]
            groups.append(tuple(sorted(self.rank_of(c) for c in itertools.product(*ranges))))
        groups.sort(key=lambda g: g[0])
        return tuple(groups)

    def local_rank_in_group(self, dimension: str, rank: int) -> int:
        """Position of ``rank`` inside its group along ``dimension``.

        Args:
            dimension: Dimension or composite-group name.
            rank: Global rank.

        Returns:
            Index of ``rank`` within :meth:`group_ranks`.
        """
        return self.group_ranks(dimension, rank).index(rank)

    def group_source_rank(self, dimension: str, rank: int) -> int:
        """Global rank of the first member of ``rank``'s group.

        Broadcast operations use this as the source so that every rank agrees
        on who is authoritative without an extra collective.

        Args:
            dimension: Dimension or composite-group name.
            rank: Global rank.

        Returns:
            The smallest global rank in the group.
        """
        return self.group_ranks(dimension, rank)[0]

    def neighbour_ranks(self, dimension: str, rank: int) -> tuple[int, int]:
        """Return the ring predecessor and successor of ``rank`` along ``dimension``.

        Point-to-point algorithms (ring all-reduce, ring attention) need a
        consistent ring order; this provides it without every call site
        re-deriving the arithmetic.

        Args:
            dimension: Dimension or composite-group name.
            rank: Global rank.

        Returns:
            ``(previous_rank, next_rank)`` as *global* ranks.  With a group of
            size one both entries are ``rank`` itself.
        """
        ranks = self.group_ranks(dimension, rank)
        index = ranks.index(rank)
        size = len(ranks)
        return ranks[(index - 1) % size], ranks[(index + 1) % size]

    # -- sequence-parallel resolution ---------------------------------------
    @property
    def sequence_group_name(self) -> str:
        """Name of the group the sequence dimension is actually split over.

        In :attr:`SequenceParallelMode.TENSOR_GROUP` this is ``"tensor"``,
        because sequence parallelism reuses the tensor-parallel ranks.  In
        ``independent`` mode it is ``"sequence"``.  When sequence parallelism
        is disabled the name is still ``"sequence"`` but the group has size 1,
        so every sequence-parallel collective degenerates to a no-op.
        """
        if self._config.sequence_parallel_mode == SequenceParallelMode.TENSOR_GROUP:
            return "tensor"
        return "sequence"

    @property
    def sequence_parallel_size(self) -> int:
        """Effective number of ranks the sequence dimension is split over."""
        return self.size(self.sequence_group_name)

    @property
    def sequence_parallel_enabled(self) -> bool:
        """``True`` when activations are actually split along the sequence axis."""
        return self._config.sequence_parallel_enabled

    # -- description --------------------------------------------------------
    def describe(self, rank: int) -> str:
        """Return a multi-line description of ``rank``'s place in the grid.

        Args:
            rank: Global rank.

        Returns:
            Human-readable text listing the coordinates and every group the
            rank belongs to.  Used by the examples and by failure diagnostics.
        """
        coords = self.coordinates_of(rank)
        lines = [
            f"rank {rank}/{self._world_size}  coordinates {coords.label()}",
            "  sizes: " + ", ".join(f"{d}={self._sizes[d]}" for d in DIMENSIONS),
            f"  sequence-parallel mode: {self._config.sequence_parallel_mode} "
            f"(effective size {self.sequence_parallel_size})",
        ]
        for name in (*DIMENSIONS, *COMPOSITE_GROUPS):
            members = self.group_ranks(name, rank)
            lines.append(
                f"  {name:<16} size={len(members):<3} "
                f"local_rank={members.index(rank):<3} members={members}"
            )
        return "\n".join(lines)

    def summary(self) -> dict[str, object]:
        """Return a JSON-serialisable description of the topology itself.

        Used as checkpoint metadata so a reader can tell what layout produced
        the shards.
        """
        return {
            "world_size": self._world_size,
            "sizes": dict(self._sizes),
            "sequence_parallel_mode": self._config.sequence_parallel_mode,
            "dimension_order": list(DIMENSIONS),
        }

    # -- internals ----------------------------------------------------------
    def _resolve(self, dimension: str) -> tuple[str, ...]:
        """Map a dimension or composite-group name to its member dimensions."""
        if dimension in DIMENSIONS:
            return (dimension,)
        if dimension in COMPOSITE_GROUPS:
            return COMPOSITE_GROUPS[dimension]
        raise TopologyError(
            format_error(
                "topology.resolve",
                "unknown dimension or group name",
                expected=sorted({*DIMENSIONS, *COMPOSITE_GROUPS}),
                observed=dimension,
                resolution="use a dimension name or a composite group name",
            )
        )

    def _check_rank(self, rank: int) -> None:
        """Validate that ``rank`` is inside the grid."""
        if not 0 <= rank < self._world_size:
            raise TopologyError(
                format_error(
                    "topology.check_rank",
                    "rank outside the topology",
                    world_size=self._world_size,
                    expected=f"0 <= rank < {self._world_size}",
                    observed=rank,
                    resolution="the topology was built for a different world size",
                )
            )

    def __repr__(self) -> str:
        sizes = ", ".join(f"{d}={self._sizes[d]}" for d in DIMENSIONS)
        return f"ParallelTopology(world_size={self._world_size}, {sizes})"
